disabled_rules:
  - trailing_comma
opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_parameter_alignment_on_call
line_length: 140
type_body_length: 400
file_length: 500
function_body_length: 80
identifier_name:
  min_length: 1
  excluded:
    - id
    - x
    - y
excluded:
  - .build
